### ISSUE TITLE
DSS CAPI for Golang 

### ISSUE THREAD

**Issue by dougchristie-DukeEnergy** [dss-extensions/dss-extensions#33]
I am wondering if there has been any discussion in the writing a DSS extension for Golang?  We are working on application in go where we would like to use DSS.

**Comment by PMeira** [comment]
From some private messages, I think some users were using Go with DSS C-API since 2019, but I imagine they only worked on a subset of the API, and it's private code since I couldn't find public repos on GitHub.

We could try to add full support in a few weeks, some thoughts:

- cgo should be enough to handle the basics
- We need some functions to map the arrays and strings from the array pointers to Go structures. Some basic usage notes: https://github.com/dss-extensions/dss_capi/blob/master/docs/usage.md#immediate-result-ir-classic-updated-in-v0100 (the existing bindings for other languages are also good examples)
- With those in place, most of the remaining code that is required would be trivial (and maybe automated).
- The most time-consuming task would be writing tests.

> We are working on application in go where we would like to use DSS.

Do you already have a usage pattern in mind? e.g. which APIs would be used, etc. We could work a smaller proof-of-concept before investing time on all the API functions.

**Comment by dougchristie-DukeEnergy** [comment]
![image](https://github.com/dss-extensions/dss-extensions/assets/126599516/ef831f54-4050-4e16-a0b0-402285a4544e)

**Comment by PMeira** [comment]
I ran some basic tests and it shouldn't be too hard to get most of the API exposed (somewhat) nicely. Cgo is indeed enough for most stuff, we don't need third-party packages for a first implementation.

Updated notes:
- Initially we would expose the basic/classic API that mimics the original COM interface (+ the basic API extensions); functions from the families `Obj_*`, `Batch_*`, and the new `Alt_*`, would be exposed later.
- Most of the non-`ctx_*` functions aren't required, in fact they will be dropped later (or moved to an optional lib).
- For a first iteration, I personally won't test multi-threading since I'm not familiar enough with Go's implementation right now. But, by using the `ctx_*` functions, it may just work with minimal issues since it works in other languages.
- The more recent releases of DSS C-API support returning shapes for 2D arrays, but that's something that doesn't seem to map directly to Go's 2D arrays. Needs some testing to see if it could be done without too much overhead, so it's better to use plain 1D arrays initially.
- Since we already have mapped most functions that return complex numbers, it could be useful to expose complex128 arrays from the start (instead of plain float64 arrays that need to be interpreted in pairs). If it's too much hassle, could be done later too; doesn't affect the list of the functions you listed.
- Go's a bit limited regarding language features, so we'll have to keep the getter and setter functions explicit.
- The error numbers/descriptions from the DSS Error interface should be mapped to Go errors (like the other language bindings do with exceptions) and the general organization could follow the organization of the official COM classes so users can reuse the docs and/or easily port code. Probably something like:

```golang

// ...get the main dss instance somehow (TBD)

idx, err := dss.Text.Set_Command("redirect some_circuit.dss")
if err != nil {
//...
}

idx, err := dss.ActiveCircuit.Loads.First()
if err != nil {
//...
}

err := dss.ActiveCircuit.Loads.Set_idx(10)
if err != nil {
//...
}

kva, err := dss.ActiveCircuit.Loads.Get_kva()
if err != nil {
//...
}

err := dss.ActiveCircuit.Loads.Set_kva(kva * 1.1)
if err != nil {
//...
}

// Create a new DSS engine context besides the prime one.
dss2, err := dss.NewContext()
if err != nil {
//...
}
```

@dougchristie-DukeEnergy, 
- Does that sound OK? Any suggestions?
- What's your minimum requirements regarding Go? Is Go v1.17 OK? What about OSes?

The most boring tasks would come later: 

- write a few minimal tests and examples
- write installation and usage notes since we need to download the DSS C-API binaries (currently only shared libraries)
- adjust comments for GoDoc
- maybe CI stuff
- multi-threading tests and examples

Medium term, after all is done, the maintenance required should minimal, so we could investigate adding the new API too (`Obj/Batch/Alt*` functions) if there is interest from more users. Right now that's still under development anyway.

**Comment by dougchristie-DukeEnergy** [comment]
All that sounds great. We are planning to use Go 1.23.+ if that is ok with you. Any idea how when you might be able to start?

**Comment by abrown7100** [comment]
> All that sounds great. We are planning to use Go 1.23.+ if that is ok with you. Any idea how when you might be able to start?

We are currently using Go `1.21.3` but we have the ability to change our versions on a per-project basis. 
@PMeira in regards to your question about OS, we're developing using Ubuntu 22.04 and deploying to just `x86_64-linux-gnu` (basically just 64bit linux containers). I work with @dougchristie-DukeEnergy BTW

**Comment by PMeira** [comment]
> Any idea how when you might be able to start?

@dougchristie-DukeEnergy If nothing more urgent shows up, we should have an initial version by Dec 8 or 11.

I'm finishing testing/fixing other changes (related to JSON Schema and the new API). Hopefully will be done with most of those today or tomorrow.

>  we're developing using Ubuntu 22.04

@abrown7100 Thanks for the info. I can focus on Linux initially then.  
I asked about Go v1.17 mostly since that is when some QoL FFI functions were introduced, anything newer should be fine.

By the way, it seems your usage would benefit from incremental Y matrix updates. I don't think we have documentation about it yet, so please ask about it later so we can add something. It can result in speedups on the order of 4x.

**Comment by PMeira** [comment]
@dougchristie-DukeEnergy @abrown7100 Just an update -- nearly done: almost all of the API is exposed nicely, including multiple DSS instances, complex numbers, etc. Two main remaining aspects:

- Packaging, aux. scripts and general repo structure. It needs to download the DSS C-API binaries somehow (or build them). The main Golang code is basically a single file with no dependencies. The main hurdle is that CGo is used.
- Decide how to expose the enums (integers). Currently left as plain int32, but constants will be safer and a better user experience in general.

Regardless of these two, I'll publish the code by tomorrow since it already is useful and the main aspects of code shouldn't change much. New version of DSS C-API incoming too!

**Comment by PMeira** [comment]
@dougchristie-DukeEnergy @abrown7100 Initial repo is at https://github.com/dss-extensions/AltDSS-Go

I'll try to add this after I finish some other tasks:

> Decide how to expose the enums (integers). Currently left as plain int32, but constants will be safer and a better user experience in general.

**Comment by dougchristie-DukeEnergy** [comment]
Hi Paulo 

Thanks for all the work. I have been working on implementing our code using DSS extensions.  I was trying to figure out how to call Solution_Set_Mode  what structure is that under?   Is there anyway to get a doc on which functions are under which DSS objects? Thanks

**Comment by PMeira** [comment]
Besides the lack of properties in Golang, it mimics the classes of the official COM objects. Check the official OpenDSS documentation, e.g. the COM help file: https://github.com/orgs/dss-extensions/discussions/31 -- there's also a new .CHM file at https://sourceforge.net/p/electricdss/code/HEAD/tree/trunk/Version8/Distrib/Doc/ (seems to be work-in-progress though) -- this new CHM is very recent, older revisions have a lot of PDFs that could be useful: https://sourceforge.net/p/electricdss/code/3706/tree/trunk/Version8/Distrib/Doc/

There's a table at the end here that could help: https://dss-extensions.org/python_apis.html 

The [DSS-Python docs](https://dss-extensions.org/dss_python/) could be of some use, or maybe [DSS Sharp's](https://dss-extensions.org/dss_sharp/)

If you're new to OpenDSS APIs, there are some annoyances in what I call "classic" APIs, the ones based on the COM implementation at some point. For example, when you "activate" a generator object, you have to use `DSS.ActiveCircuit.Generators` for some of the API, `DSS.ActiveCircuit.ActiveCktElement` for some other part, etc. The main issue is, if you activate any other object like from `DSS.ActiveCircuit.Transformers`, it changes `ActiveCktElement` too, etc. So, usually you're only safe to operate on a single object.

Besides that, not all DSS object types are exposed in the classic API. Sometimes you may need to use the plain text API (`DSS.Text.Command` and `DSS.Text.Result`). But, per your initial messages, I think most of the stuff you'd need is accessible without it.

The classic APIs will stay for a long while for better compatibility with the official distribution of OpenDSS, especially since we want to support the official binaries too, soon (they have a more limited API, and currently only work on Windows). The new API I mentioned in earlier messages expose all object types, does away with the `Active...` idiom (you get a pointer to the object, which we track to guarantee it's only used in the correct lifetime), exposes batches of objects for easier manipulation, plus merges all separate parts, so basically `AltDSS.Generator` would expose all generators, including all related CktElement functions and so on. I'll probably work on exposing that to Go and other languages in January, since I'm sure it will make both learning and using the DSS engine much more comfortable.

**Comment by PMeira** [comment]
EPRI just published their docs online too, it could help a bit here: https://opendss.epri.com/opendss_documentation.html

Closing this issue since our golang repo is live at https://github.com/dss-extensions/AltDSS-Go/ and we can track things better there.
